# Generated by Django 5.1.5 on 2025-02-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pagina_squalo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Usuarios',
        ),
    ]
